# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mamori < Formula
  desc "CLI for the mamori typed config and secrets library: explain, schema, policy, doctor, status"
  homepage "https://mamorigo.dev"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xavidop/mamori/releases/download/v1.2.2/mamori_1.2.2_darwin_amd64.tar.gz"
      sha256 "893ab556028338e18ce8cd4296935c078512f34eb96bef3a9906c08acd1bc930"

      define_method(:install) do
        bin.install "mamori"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xavidop/mamori/releases/download/v1.2.2/mamori_1.2.2_darwin_arm64.tar.gz"
      sha256 "3a15a57a6097a812e72a4e085da20c6fa612ff4dbe23c6b26bcbb27cb2c0a427"

      define_method(:install) do
        bin.install "mamori"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/mamori/releases/download/v1.2.2/mamori_1.2.2_linux_amd64.tar.gz"
      sha256 "c633faf2429af2985e182dbf70c3abeba6862fa70a8e722a5029fcce425af3f8"
      define_method(:install) do
        bin.install "mamori"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/mamori/releases/download/v1.2.2/mamori_1.2.2_linux_arm64.tar.gz"
      sha256 "fee4105e9d3909119fe4a18780b196ef4b701f169a25ee1f7ad0356a3e4fec93"
      define_method(:install) do
        bin.install "mamori"
      end
    end
  end

  test do
    system "#{bin}/mamori", "version"
  end
end
