# This file was generated by GoReleaser. DO NOT EDIT.
cask "diamond" do
  version "1.18.3"

  on_macos do
    on_arm do
      sha256 "b4caeffce04cbc8535693385f60f51dc51214a726e40fea43f85d585a246e27e"
      url "https://github.com/xavidop/diamond/releases/download/v#{version}/diamond_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "766906703e6fdf667827eddaf6300d236c2bd425f5e64e39c3e0e46d9879a107"
      url "https://github.com/xavidop/diamond/releases/download/v#{version}/diamond_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ded2984a122a6deaed5a7ca570b1b078cc54663e5557a98a224203ac3e9561dc"
      url "https://github.com/xavidop/diamond/releases/download/v#{version}/diamond_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "234ede1ecc9057913cf48195eb96e311f13333b8663e7167e451c4bc415c888c"
      url "https://github.com/xavidop/diamond/releases/download/v#{version}/diamond_#{version}_linux_amd64.tar.gz"
    end
  end

  name "diamond"
  desc "⚾ MLB stats in your terminal"
  homepage "https://github.com/xavidop/diamond"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "diamond"

  postflight_steps do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/diamond"]
    end
  end

  # No zap stanza required
end
