# This file was generated by GoReleaser. DO NOT EDIT.
cask "diamond" do
  version "1.9.0"

  on_macos do
    on_intel do
      sha256 "42d66e88eb4ba8055a0c45f54ea300ca2599206942b3093af4198c8ef91b5886"
      url "https://github.com/xavidop/diamond/releases/download/v#{version}/diamond_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4cf4335f13fc7d5e18dd6bc64b126dec62dd9ec5ea8fbd6ce359d0be7c445940"
      url "https://github.com/xavidop/diamond/releases/download/v#{version}/diamond_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "995c98aedeeb39020ea1f46e4811e95d550a363a48985e239bac8df1c160d5dd"
      url "https://github.com/xavidop/diamond/releases/download/v#{version}/diamond_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ac8ba7fcffe521cb8a2c9dad0c1c6c19895becb8288460536e15abafd8adc371"
      url "https://github.com/xavidop/diamond/releases/download/v#{version}/diamond_#{version}_linux_arm64.tar.gz"
    end
  end

  name "diamond"
  desc "⚾ MLB stats in your terminal"
  homepage "https://github.com/xavidop/diamond"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "diamond"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/diamond"]
    end
  end

  # No zap stanza required

end
