# This file was generated by GoReleaser. DO NOT EDIT.
cask "diamond" do
  version "1.11.0"

  on_macos do
    on_intel do
      sha256 "2e223cdeef7eaba7f6e8a548327d458d22e0dfb1394721f18ea9ab40ac66215e"
      url "https://github.com/xavidop/diamond/releases/download/v#{version}/diamond_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b187fe9558004408db93d5d53a539011dbec73b5bc4569686f82b3a4d733b9b7"
      url "https://github.com/xavidop/diamond/releases/download/v#{version}/diamond_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd6b7fa1512a625b0ea92cfb5ab332f9a5a59231ea8b2c4fabea325fb799da12"
      url "https://github.com/xavidop/diamond/releases/download/v#{version}/diamond_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "61a4255f08fde130bf51e696e006a656107b25605811314e0da1d794e748d97c"
      url "https://github.com/xavidop/diamond/releases/download/v#{version}/diamond_#{version}_linux_arm64.tar.gz"
    end
  end

  name "diamond"
  desc "⚾ MLB stats in your terminal"
  homepage "https://github.com/xavidop/diamond"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "diamond"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/diamond"]
    end
  end

  # No zap stanza required

end
