# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cxtester < Formula
  desc "Google action CLI utility for create Google Actions from CSV files"
  homepage "https://github.com/xavidop/dialogflow-cx-test-runner"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xavidop/dialogflow-cx-test-runner/releases/download/v1.3.0/darwin_amd64_v1.3.0.tar.gz"
      sha256 "9cde62ce14f803b83eccaca5dce13475aa02a5e1cc96a81ba1552a5a94aafeb2"

      def install
        bin.install "cxtester"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xavidop/dialogflow-cx-test-runner/releases/download/v1.3.0/darwin_arm64_v1.3.0.tar.gz"
      sha256 "88e42f36d4086730876a134dd9b85628edd36f2d4b41e7b9c89a8244897b56a1"

      def install
        bin.install "cxtester"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/dialogflow-cx-test-runner/releases/download/v1.3.0/linux_arm64_v1.3.0.tar.gz"
      sha256 "6210ffae58c6e5ba61b05c974387db1502b5918051dd8a7f0d221a8ec65a2be2"

      def install
        bin.install "cxtester"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/xavidop/dialogflow-cx-test-runner/releases/download/v1.3.0/linux_amd64_v1.3.0.tar.gz"
      sha256 "e1c4ccd4c496f83fb860b7ee58bbf42355d69a47df3c1dd13ba9f42270d94aac"

      def install
        bin.install "cxtester"
      end
    end
  end
end
