# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoogleActionTypeImporter < Formula
  desc "Google action CLI utility for create Google Actions from CSV files"
  homepage "https://github.com/xavidop/google-action-type-importer"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xavidop/google-action-type-importer/releases/download/v1.0.0/darwin_amd64_v1.0.0.tar.gz"
      sha256 "b1372abf8b6e11762fc255c5b45f449e5909d5dc171f3a5ec2f84021b6ae8905"

      def install
        bin.install "google-action-type-importer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xavidop/google-action-type-importer/releases/download/v1.0.0/darwin_arm64_v1.0.0.tar.gz"
      sha256 "cedfd8a1211d484089d890ce5d486243581c0fcb14b125ecce2a2fb4fc440187"

      def install
        bin.install "google-action-type-importer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/xavidop/google-action-type-importer/releases/download/v1.0.0/linux_amd64_v1.0.0.tar.gz"
      sha256 "c895a69bd2fb799fba32c080d2aaf0f5ebcba7e79e01835a4b6ba4f3bbde53f8"

      def install
        bin.install "google-action-type-importer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/google-action-type-importer/releases/download/v1.0.0/linux_arm64_v1.0.0.tar.gz"
      sha256 "d8821f9f377d2e27d7537cac0d89614c4089d8f76b49a52bb69e2e3d125bec0e"

      def install
        bin.install "google-action-type-importer"
      end
    end
  end
end
