# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mamori < Formula
  desc "CLI for the mamori typed config and secrets library: explain, schema, policy, doctor, status"
  homepage "https://mamorigo.dev"
  version "1.12.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xavidop/mamori/releases/download/v1.12.3/mamori_1.12.3_darwin_amd64.tar.gz"
      sha256 "2b86feb7205ba08c46a2c7296a70cd1899a32e49764587ed51fd26aa09206487"

      define_method(:install) do
        bin.install "mamori"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xavidop/mamori/releases/download/v1.12.3/mamori_1.12.3_darwin_arm64.tar.gz"
      sha256 "b285f6730a7abd9df840a4c194eb0b0e4a5d99233dfaaaf232cc02923724c6f5"

      define_method(:install) do
        bin.install "mamori"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/mamori/releases/download/v1.12.3/mamori_1.12.3_linux_amd64.tar.gz"
      sha256 "714f41b7c89c46e8d36efe146d3d2a34d078fe2627c30d250c2d56f86cb94da0"
      define_method(:install) do
        bin.install "mamori"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/mamori/releases/download/v1.12.3/mamori_1.12.3_linux_arm64.tar.gz"
      sha256 "bcb0cada77d0db5b6e2f63d5ae1323987fbfcfd9ce07c15a530807fef76ed337"
      define_method(:install) do
        bin.install "mamori"
      end
    end
  end

  test do
    system "#{bin}/mamori", "version"
  end
end
