# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mamori < Formula
  desc "CLI for the mamori typed config and secrets library: explain, schema, policy, doctor, status"
  homepage "https://mamorigo.dev"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xavidop/mamori/releases/download/v1.8.0/mamori_1.8.0_darwin_amd64.tar.gz"
      sha256 "4d15609f53e14f4e5990f8ba1f8c040c106048b588d0cb8cad9d04493d12f3e0"

      define_method(:install) do
        bin.install "mamori"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xavidop/mamori/releases/download/v1.8.0/mamori_1.8.0_darwin_arm64.tar.gz"
      sha256 "e4daa1c72e944a7f711e81211645dfe4800fb1bf353311001eb1426a188c5212"

      define_method(:install) do
        bin.install "mamori"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/mamori/releases/download/v1.8.0/mamori_1.8.0_linux_amd64.tar.gz"
      sha256 "b7b16f2bd2c29cdcb0c1e10f377ac4985baf4e5d841a815dbbabfc4d579607f8"
      define_method(:install) do
        bin.install "mamori"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/mamori/releases/download/v1.8.0/mamori_1.8.0_linux_arm64.tar.gz"
      sha256 "77198de9aadbe5d954a33a96a646312835e773bf607ffdec02902bbdd0efb9bb"
      define_method(:install) do
        bin.install "mamori"
      end
    end
  end

  test do
    system "#{bin}/mamori", "version"
  end
end
