# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Senro < Formula
  desc "CLI for the senro pipeline engine: build and run a pipeline, attach to a live or finished run, and follow it from the terminal"
  homepage "https://github.com/xavidop/senro"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xavidop/senro/releases/download/v1.0.1/senro_1.0.1_darwin_amd64.tar.gz"
      sha256 "56ad08731bae989ad22193efaac107aac95850faca6e0b7dd2783d149f527b59"

      define_method(:install) do
        bin.install "senro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xavidop/senro/releases/download/v1.0.1/senro_1.0.1_darwin_arm64.tar.gz"
      sha256 "6b9e24ba6a189b50135a4e33b1e6f3f134a990d2a5da32bd5c3fe94e0094bd64"

      define_method(:install) do
        bin.install "senro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/senro/releases/download/v1.0.1/senro_1.0.1_linux_amd64.tar.gz"
      sha256 "3a395838dbddd645ea62b014d31bbcdba6a509a9e3cefa3873c7983783325295"
      define_method(:install) do
        bin.install "senro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/senro/releases/download/v1.0.1/senro_1.0.1_linux_arm64.tar.gz"
      sha256 "7581ad1e45eb6a3b5b3b32232f048e888eb57e946138f587c53f0f13859e309e"
      define_method(:install) do
        bin.install "senro"
      end
    end
  end

  test do
    # `senro version` does not exist in this build (see cmd/senro/main.go's
    # usage: run, attach, ui, help; no version subcommand). --help is the
    # one invocation guaranteed to exist, print something senro-specific,
    # and exit 0, so it is what actually proves the installed binary works.
    assert_match "senro is the CLI companion", shell_output("#{bin}/senro --help")
  end
end
