# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Senro < Formula
  desc "CLI for the senro pipeline engine: build and run a pipeline, attach to a live or finished run, and follow it from the terminal"
  homepage "https://github.com/xavidop/senro"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xavidop/senro/releases/download/v1.4.0/senro_1.4.0_darwin_amd64.tar.gz"
      sha256 "cfef82b8e205202cd4e0db01f8b1eee6a92066a7b6dfa552470440e5d6652415"

      define_method(:install) do
        bin.install "senro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xavidop/senro/releases/download/v1.4.0/senro_1.4.0_darwin_arm64.tar.gz"
      sha256 "41966f59a54cc3962099fc06ad89b2c8d5002665003b9a759dafd364bdbb7343"

      define_method(:install) do
        bin.install "senro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/senro/releases/download/v1.4.0/senro_1.4.0_linux_amd64.tar.gz"
      sha256 "237eea9c2466c9dd3635b9702e70c962acab9e2ba7b6db8f7c10d7b172199539"
      define_method(:install) do
        bin.install "senro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/senro/releases/download/v1.4.0/senro_1.4.0_linux_arm64.tar.gz"
      sha256 "135e4bb07cf547aca64592f233756a7d65483c3992d714eb3ec35dfe781c39c9"
      define_method(:install) do
        bin.install "senro"
      end
    end
  end

  test do
    # `senro version` does not exist in this build (see cmd/senro/main.go's
    # usage: run, attach, ui, help; no version subcommand). --help is the
    # one invocation guaranteed to exist, print something senro-specific,
    # and exit 0, so it is what actually proves the installed binary works.
    assert_match "senro is the CLI companion", shell_output("#{bin}/senro --help")
  end
end
