# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Senro < Formula
  desc "CLI for the senro pipeline engine: build and run a pipeline, attach to a live or finished run, and follow it from the terminal"
  homepage "https://github.com/xavidop/senro"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xavidop/senro/releases/download/v1.0.2/senro_1.0.2_darwin_amd64.tar.gz"
      sha256 "902e6d8e63416755cea416e40fe52d58f3cc43f4a7fd534cb812e4a252d13fb1"

      define_method(:install) do
        bin.install "senro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xavidop/senro/releases/download/v1.0.2/senro_1.0.2_darwin_arm64.tar.gz"
      sha256 "c59033367d08b50ffe8c512ed42baa33b1a430bbe965fb6eb690caedaf1d7c54"

      define_method(:install) do
        bin.install "senro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/senro/releases/download/v1.0.2/senro_1.0.2_linux_amd64.tar.gz"
      sha256 "91d8cc633d886e0cc677b2e2bdb6565b3c8b1fbb36ed7f68923e16f19bff0823"
      define_method(:install) do
        bin.install "senro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/senro/releases/download/v1.0.2/senro_1.0.2_linux_arm64.tar.gz"
      sha256 "180439db4e47e1a543cbc9ab31e7391faab9ce8322552e75662c7697bfedba5e"
      define_method(:install) do
        bin.install "senro"
      end
    end
  end

  test do
    # `senro version` does not exist in this build (see cmd/senro/main.go's
    # usage: run, attach, ui, help; no version subcommand). --help is the
    # one invocation guaranteed to exist, print something senro-specific,
    # and exit 0, so it is what actually proves the installed binary works.
    assert_match "senro is the CLI companion", shell_output("#{bin}/senro --help")
  end
end
