# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Voiceflow < Formula
  desc "The CLI for your Voiceflow projects"
  homepage "https://voiceflow.xavidop.me"
  version "1.6.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.6.2/voiceflow_Darwin_x86_64.tar.gz"
      sha256 "4233c52e52976fea0b343951c902ff6014aee892af02c6fe6db4f2bd88478eb8"

      def install
        bin.install "voiceflow"
        bash_completion.install "completions/voiceflow.bash" => "voiceflow"
        zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
        fish_completion.install "completions/voiceflow.fish"
        man1.install "manpages/voiceflow.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.6.2/voiceflow_Darwin_arm64.tar.gz"
      sha256 "274f45cee0f62822f72d1cdcf0c70f5420a6f9885e5697206220fdaccdf00e4c"

      def install
        bin.install "voiceflow"
        bash_completion.install "completions/voiceflow.bash" => "voiceflow"
        zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
        fish_completion.install "completions/voiceflow.fish"
        man1.install "manpages/voiceflow.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.6.2/voiceflow_Linux_x86_64.tar.gz"
        sha256 "5144c86aa6fbb21a4fc79ff898e4d2d0c34e1a59b01e52ecab2519dbf9e6f658"

        def install
          bin.install "voiceflow"
          bash_completion.install "completions/voiceflow.bash" => "voiceflow"
          zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
          fish_completion.install "completions/voiceflow.fish"
          man1.install "manpages/voiceflow.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.6.2/voiceflow_Linux_armv7.tar.gz"
        sha256 "b752ca8ba1347191feb63bab8d3fe8e1a23dffe84e9636a72a2eff7aec192dcb"

        def install
          bin.install "voiceflow"
          bash_completion.install "completions/voiceflow.bash" => "voiceflow"
          zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
          fish_completion.install "completions/voiceflow.fish"
          man1.install "manpages/voiceflow.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.6.2/voiceflow_Linux_arm64.tar.gz"
        sha256 "648390ef04f342644f3c36fd7afd6ebb31f8fe6cb0732872e9df5da34ed0e7a6"

        def install
          bin.install "voiceflow"
          bash_completion.install "completions/voiceflow.bash" => "voiceflow"
          zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
          fish_completion.install "completions/voiceflow.fish"
          man1.install "manpages/voiceflow.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/voiceflow version"
  end
end
