# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Voiceflow < Formula
  desc "The CLI for your Voiceflow projects"
  homepage "https://voiceflow.xavidop.me"
  version "1.27.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.27.0/voiceflow_Darwin_x86_64.tar.gz"
      sha256 "29d42bd8dbe076c9407a45ffcf9eaa7ce10188231ea1d740b377f1cab4b81514"

      def install
        bin.install "voiceflow"
        bash_completion.install "completions/voiceflow.bash" => "voiceflow"
        zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
        fish_completion.install "completions/voiceflow.fish"
        man1.install "manpages/voiceflow.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.27.0/voiceflow_Darwin_arm64.tar.gz"
      sha256 "09c81dde89c9dfb54bc69d2af37c3ccd39b5f02f32f278838c2755ad864529b9"

      def install
        bin.install "voiceflow"
        bash_completion.install "completions/voiceflow.bash" => "voiceflow"
        zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
        fish_completion.install "completions/voiceflow.fish"
        man1.install "manpages/voiceflow.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.27.0/voiceflow_Linux_x86_64.tar.gz"
      sha256 "d21ad9b4f8c3cf73373eae54625cd76cf4c91f87ecb9094fc249f2848ad11a6c"
      def install
        bin.install "voiceflow"
        bash_completion.install "completions/voiceflow.bash" => "voiceflow"
        zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
        fish_completion.install "completions/voiceflow.fish"
        man1.install "manpages/voiceflow.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.27.0/voiceflow_Linux_armv7.tar.gz"
      sha256 "9b2bece241f9af7e38a460e3f843fabe4ad9d7b3b6e9d9051ae760172dd1b0ad"
      def install
        bin.install "voiceflow"
        bash_completion.install "completions/voiceflow.bash" => "voiceflow"
        zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
        fish_completion.install "completions/voiceflow.fish"
        man1.install "manpages/voiceflow.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.27.0/voiceflow_Linux_arm64.tar.gz"
      sha256 "395d09e7d5f32779efb4d58b8bccbe866a3c33ddbd9ff89213e910f56458a0ae"
      def install
        bin.install "voiceflow"
        bash_completion.install "completions/voiceflow.bash" => "voiceflow"
        zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
        fish_completion.install "completions/voiceflow.fish"
        man1.install "manpages/voiceflow.1.gz"
      end
    end
  end

  test do
    system "#{bin}/voiceflow version"
  end
end
