# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Voiceflow < Formula
  desc "The CLI for your Voiceflow projects"
  homepage "https://voiceflow.xavidop.me"
  version "1.10.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.10.4/voiceflow_Darwin_x86_64.tar.gz"
      sha256 "7f99ff7d1b05d4a910fc1963d30708227a9685e374972c4c716ec7fd9b48aff7"

      def install
        bin.install "voiceflow"
        bash_completion.install "completions/voiceflow.bash" => "voiceflow"
        zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
        fish_completion.install "completions/voiceflow.fish"
        man1.install "manpages/voiceflow.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.10.4/voiceflow_Darwin_arm64.tar.gz"
      sha256 "9718474f4981a19758774876a82027e4ee453465cec5035ba424252484536dff"

      def install
        bin.install "voiceflow"
        bash_completion.install "completions/voiceflow.bash" => "voiceflow"
        zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
        fish_completion.install "completions/voiceflow.fish"
        man1.install "manpages/voiceflow.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.10.4/voiceflow_Linux_x86_64.tar.gz"
        sha256 "e68016d083bf70e8ad6a74735ca9a98593de2c1869caad1f525de25ecb061c56"

        def install
          bin.install "voiceflow"
          bash_completion.install "completions/voiceflow.bash" => "voiceflow"
          zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
          fish_completion.install "completions/voiceflow.fish"
          man1.install "manpages/voiceflow.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.10.4/voiceflow_Linux_armv7.tar.gz"
        sha256 "3ec7e4ef6a5f0d7166257303ccb102f97242ffa44fe31f1329c01233cd7cf7b0"

        def install
          bin.install "voiceflow"
          bash_completion.install "completions/voiceflow.bash" => "voiceflow"
          zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
          fish_completion.install "completions/voiceflow.fish"
          man1.install "manpages/voiceflow.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xavidop/voiceflow-cli/releases/download/v1.10.4/voiceflow_Linux_arm64.tar.gz"
        sha256 "248c02d835c7447d32823ed92fdacdd5ae824c2138e710518b7809b64ece7c53"

        def install
          bin.install "voiceflow"
          bash_completion.install "completions/voiceflow.bash" => "voiceflow"
          zsh_completion.install "completions/voiceflow.zsh" => "_voiceflow"
          fish_completion.install "completions/voiceflow.fish"
          man1.install "manpages/voiceflow.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/voiceflow version"
  end
end
